### ISSUE TITLE
Convert can't find coffee file

### ISSUE THREAD

**Issue by zachberry** [decaffeinate/bulk-decaffeinate#120]
I was able to get `check` to run successfully but after running `convert` I get this output:

```
Generating the first commit: "decaffeinate: Rename componentclassmap.coffee and 194 other files from .coffee to .js"...
fatal: pathspec '/my-project/src/scripts/node_modules/Viewer/index.coffee' did not match any files

Error: fatal: pathspec '/my-project/src/scripts/node_modules/Viewer/index.coffee' did not match any files

    at /usr/local/lib/node_modules/bulk-decaffeinate/node_modules/simple-git/promise.js:21:26
    at Git.<anonymous> (/usr/local/lib/node_modules/bulk-decaffeinate/node_modules/simple-git/src/git.js:1169:18)
    at Git.<anonymous> (/usr/local/lib/node_modules/bulk-decaffeinate/node_modules/simple-git/src/git.js:1243:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

It seems to be trying to find `index.coffee` but only `index.original.coffee` exists, hence the error

**Comment by alangpierce** [comment]
Interesting, I haven't seen this before. There's a daily build of a bunch of CoffeeScript project that's still working, so I think things aren't totally broken.

A few questions:

* Did you run this before and it worked, and now it doesn't? I made some changes to this stuff in the last few days, so would be nice to know if this broke recently or has always been an issue.
* Why are you running decaffeinate on files in a `node_modules` directory? Probably you should only run it on files directly in your project.
* How are you specifying the files to process? bulk-decaffeinate is supposed to skip any files in a `node_modules` directory when it auto-discovers files.

My best guess here is that you're trying to run bulk-decaffeinate on files that aren't in your git repo. I think it's reasonable for it to fail in that case, but probably there should be a more clear error message.

**Comment by zachberry** [comment]
The first run was today. I do have some files in a node_modules directory that isn't my primary node_modules directory, if that makes sense. So my project's structure is similar to this:

```
package.json
node_modules
src
    some-files.coffee
    node_modules <-- internal node_modules directory
        app-module-1
            module-1-files.coffee
        app-module-2
            module-2-files.coffee
```

(In the end this lets me do `require('app-module-1/module-1-files.coffee')` instead of prefixing with `../../../`) - more info: https://github.com/substack/browserify-handbook#how-node_modules-works

At any rate, based on your comment I'm assuming this admittedly uncommon use case may be causing my issue?

**Comment by alangpierce** [comment]
Makes sense about your project structure. I hadn't seen that particular approach to "absolute imports", but makes sense. In your example `app-module-1` and `app-module-2` are directly in your git repo, right (not symlinks)?

I just released a change that makes the error reporting nicer in situations like these and makes auto-discovery skip untracked files. Hopefully that should at least make it easier to figure out what's going on. My impression is that it should be possible to get your use case to work, although I think it would require giving bulk-decaffeinate a list of files to convert since the auto-discovery process skips directories called `node_modules`.
