### ISSUE TITLE
should allow config file location to be specified

### ISSUE THREAD

**Issue by bpytlik** [decaffeinate/bulk-decaffeinate#121]
Afaict, there's currently no cli option that allows a config file that lives outside of the current directory to be specified. Having such an option would allow people to have a central config file specifying how they want to decaffeinate without having to copy it into each location that's being decaffeinated.

**Comment by alangpierce** [comment]
Thanks for reporting! This should be fixed now. One thing to note is that any relative paths are still resolved relative to the working directory, not relative to the config file directory.

Out of curiosity, what config settings did you want shared between projects? Ideally, the defaults would be good enough that bulk-decaffeinate settings should be mostly project-specific.

**Comment by bpytlik** [comment]
Great, I'll give that a try and see what happens. The resolution of relative paths is fine, I can always use __dirname to get paths relative to the config file if I need it.

In my case, I needed to set a decaffeinateArg (keep-commonjs) as well as set the decaffeinate and eslint paths (b/c we have a non-standard directory layout for our development node modules).

**Comment by alangpierce** [comment]
Cool, makes sense. FYI I'm planning to change `--keep-commonjs` to be the default in the near future, so that should get rid of the need to specify it in your config.
