### ISSUE TITLE
Not skipping eslint step gracefully when config is missing

### ISSUE THREAD

**Issue by theGrue** [decaffeinate/bulk-decaffeinate#134]
It looks like the code makes an attempt to gracefully skip the eslint step when a configuration is not found: https://github.com/decaffeinate/bulk-decaffeinate/blob/master/src/modernize/runEslintFix.js#L37

In practice, I'm receiving this output:
```
Running eslint --fix on all files...

Error while running eslint:
```

It seems like all the conversion is done, but it confused me at first and made me think the decaffeinate process had errored out prematurely.

I'm running on Mac OS X 10.12.6, Node 6.11.2, and eslint 4.5.0 (installed globally, not installed in project being decaffeinated).

**Comment by alangpierce** [comment]
Thanks for reporting, I think the issue is that eslint now reports the error on stderr and I'm checking stdout. Should hopefully be an easy fix.
