### ISSUE TITLE
Windows: "'.' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by laurence-myers** [decaffeinate/bulk-decaffeinate#143]
Attempting to run `bulk-caffeinate check` on Windows causes every file to fail with this error:

    '.' is not recognized as an internal or external command, operable program or batch file.

I tested this using both Windows Command Prompt and Git Bash.

Looks like the tool assumes the OS always uses forward-slash directory separators.

Rather than using hardcoded paths, I suggest all paths are constructed using "[path.join()](https://nodejs.org/api/path.html#path_path_join_paths)".

> The path.join() method joins all given path segments together using the platform specific separator as a delimiter, then normalizes the resulting path.

So, the existing code:

    nodeModulesPath = './node_modules/.bin/' + binaryName;

... becomes:

    nodeModulesPath = path.join('.', 'node_modules', '.bin', binaryName);

**Comment by alangpierce** [comment]
Thanks for reporting! Certainly the intention is for bulk-decaffeinate to work on Windows, although I don't have easy access to a Windows machine, so I've had trouble testing it. Agreed that that `path.join` makes sense in place of any hard-coded forward-slash. (TBH it would be nice if there was a prettier way to write cross-platform code, but my understanding is there's not.) I'd be happy to accept a PR to get Windows support in better shape.

**Comment by laurence-myers** [comment]
Thanks for your response! :slightly_smiling_face: 

I actually ended up writing a custom Windows batch script:
https://gist.github.com/laurence-myers/b36b0337a0e13e262a4076af63a66d4b

That script fulfilled my needs. I imagine the way I tried to use this tool was an unusual scenario, so I'm going to close this issue.

Thanks for decaffeinate, it's great! :grin:

**Comment by alangpierce** [comment]
Cool, sounds good. 😄 Yeah, bulk-decaffeinate is basically my custom shell script that I decided to productionize a bit, so it makes sense that it wouldn't handle every case.
