### ISSUE TITLE
feature: refactor land into a seperate modules

### ISSUE THREAD

**Issue by refack** [decaffeinate/bulk-decaffeinate#86]
[`nodegit`](https://github.com/nodegit/nodegit) is a dependency monster (barly buildable on windows), and provides a very specific function, that's not nececerily a main use-case.

**Comment by alangpierce** [comment]
Yeah, I've seen various problems with nodegit, e.g. #67. :-/

nodegit is used in `convert` as well, so it's not trivial to just isolate it. But it may be best to rewrite both `convert` and `land` to just shell out to `git` (which is the approach I originally took for a while).

**Comment by refack** [comment]
There are thin-wrappers, such as [`git-js`](https://github.com/steveukx/git-js)

**Comment by alangpierce** [comment]
Ooh, cool, thanks, I hadn't seen that.

**Comment by refack** [comment]
Would you mind if I give it a try (i.e. assign to me)?

**Comment by alangpierce** [comment]
@refack sure, done. The previous code in 8c78da9d63555f3b91875950210fae3b686973d5 has the original code from before I switched `convert` to nodegit. Also may be good to do things incrementally, like switch `convert` (or part of `convert`) to use git-js first. `convert` also has plenty of tests, and unfortunately `land` doesn't have tests at the moment because they were hard to write.

**Comment by alangpierce** [comment]
@refack FYI I just moved this project to the decaffeinate org, so the URL is different. I think everything should redirect just fine, but you may need/want to update your git remote.

**Comment by refack** [comment]
👍

**Comment by refack** [comment]
@alangpierce can you review my [current work](https://github.com/decaffeinate/bulk-decaffeinate/compare/v1.13.2...refack:not-nodegit). I got the `convert` test suite to go green (on my machine). So it's at a good stage.

**Comment by alangpierce** [comment]
@refack sorry for the delay! nodegit is still causing various issues, so I'm planning to move from it to simple-git based off of your branch. Your branch had a lot of changes, so I'm going to try to break it up into smaller pieces, first focusing on moving off of nodegit and then general Windows support should be a bit more manageable after that.
