### ISSUE TITLE
detect extension-less CoffeeScript scripts

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/bulk-decaffeinate#90]
The decaffeinate-examples fork of hubot still has [`bin/hubot`](https://github.com/decaffeinate-examples/hubot/blob/d0d6c16e92b0613433692ead6e2b8f5dc53b12b1/bin/hubot) as CoffeeScript because bulk-decaffeinate doesn't find it. We could pretty easily look in all extension-less files (maybe that are executable?) and look for a shebang line like this: `#!/usr/bin/env coffee`.

**Comment by alangpierce** [comment]
👍 I've got a few of those in my codebase as well, and they all have no extension and `#!/usr/bin/env coffee` at the top. Another possible option is to just have a list of additional files to process in bulk-decaffeinate.config.js.

One difficulty here is what to do with the git history. Currently the code assumes that all files end in `.coffee` and I think it assumes that the `.coffee` and `.js` files can exist at the same time, and it makes the rename operation its own commit.

Also, I guess it would make sense to modify the shebang line to run node instead? Also maybe we'd need to use babel-register, but I'd also like to avoid making those kinds of assumptions, I think.

This could also be done in more of a one-off way for each case, like renaming the file to .coffee beforehand, then renaming the .js file back and changing the shebang line afterward. For decaffeinate-examples, this could be done with a patch before and a patch after.

**Comment by eventualbuddha** [comment]
[decaffeinate already patches it to replace `coffee` with `node`](https://github.com/decaffeinate/decaffeinate/blob/b535205105c51dd37e4178df6cb082cda98374bd/src/stages/main/patchers/ProgramPatcher.js#L125), though you're right that sometimes you'll need `babel-register`.

**Comment by alangpierce** [comment]
Ah, neat, I hadn't seen that.
