### ISSUE TITLE
Output .ts files

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/bulk-decaffeinate#91]
How about an option that renames the .js files to .ts when doing the conversion? That way we wouldn't have to do yet another commit to change the files to TypeScript A more generic approach could be to allow users to specify the filetype that should be outputted. :)

**Comment by alangpierce** [comment]
@madskonradsen makes sense. Currently I'm leaning toward an optional transform at the end that generates a fourth commit renaming .js to .ts (or maybe .jsx or any other extension). It seems a little weird to run jscodeshift and eslint on .ts files, although maybe it would just work? I haven't tested. Is there a typescript configuration that lets you just have plain JS with no type annotations in .ts files and have it all work? I guess ideally the output from bulk-decaffeinate is something that would be runnable without a bunch of manual follow-up work.

The alternative, of course, is to do a one-time migration to JS through bulk-decaffeinate, then an incremental migration to typescript.
